import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@/Components/Sidebar";
import Topbar from "@/Components/Topbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "FV Admin Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div
                    className="md:grid grid-cols-5 grid-rows-5 h-screen"
                    style={{ gridColumnGap: '0px', gridRowGap: '0px' }}
                >
                    <div className="col-span-5 row-span-1">
                        <div className="md:fixed top-0 left-0 right-0 h-12 z-30">
                            <Topbar />
                        </div>
                    </div>

                    <div className="md:row-start-2 md:row-end-6 col-start-1 col-end-2">
                        <div className="md:fixed top-24 left-0 h-[calc(100vh-4rem)] md:w-64 z-40">
                            <Sidebar />
                        </div>
                    </div>

                    <div className=" md:row-start-2 md:row-end-6 md:col-start-2 md:col-end-6 -mt-5 ml-0  md:px-16 md:block relative -top-120 md:top-0 overflow-y-auto">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
